"""empty message

Revision ID: fbd586593bcb
Revises: ff06a2241a57
Create Date: 2024-07-17 09:18:36.109964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbd586593bcb'
down_revision: Union[str, None] = 'ff06a2241a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('status', postgresql.ENUM('AVAILABLE', 'BOOKED', 'MAINTENANCE', 'OCCUPIED', 'CLEANING', name='roomstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
