"""empty message

Revision ID: 64064bb123ea
Revises: fbd586593bcb
Create Date: 2024-07-17 19:00:56.409061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64064bb123ea'
down_revision: Union[str, None] = 'fbd586593bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type
    op.execute("CREATE TYPE roomtype AS ENUM ('SINGLE', 'DOUBLE', 'SUITE', 'FAMILY', 'DELUXE')")
    op.add_column('room_type_info', sa.Column('name', sa.Enum('SINGLE', 'DOUBLE', 'SUITE', 'FAMILY', 'DELUXE', name='roomtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_type_info', 'name')
    # Drop the ENUM type
    op.execute("DROP TYPE roomtype")
    # ### end Alembic commands ###
