version: '3.9'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq-data:/var/lib/rabbitmq"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  authentication_service:
    build: ./authentication_service
    command: uvicorn main:authentication_app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    depends_on:
      - authentication_database
    volumes:
      - ./authentication_service:/auth_app

  booking_service:
    build: ./booking_service
    command: uvicorn main:booking_app --host 0.0.0.0 --port 8002 --reload
    ports:
      - "8002:8002"
    depends_on:
      - booking_database
    volumes:
      - ./booking_service:/booking_app

  authentication_database:
    image: postgres:latest
    env_file:
      - ./authentication_service/.env_db
    ports:
      - "65400:5432"
    volumes:
      - postgres_authentication_database:/var/lib/postgresql/data/

  booking_database:
    image: postgres:latest
    env_file:
      - ./booking_service/.env_db
    ports:
      - "65401:5432"
    volumes:
      - postgres_booking_database:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - authentication_database
      - booking_database

volumes:
  postgres_authentication_database:
  postgres_booking_database:
