"""first migration

Revision ID: 548dfcb391b7
Revises: 
Create Date: 2024-08-02 10:58:40.285230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548dfcb391b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('reviewer_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_review_user_id_room_id'), 'review', ['user_id', 'room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_review_user_id_room_id'), 'review', type_='unique')
    op.drop_column('answer', 'reviewer_id')
    # ### end Alembic commands ###