"""first migration

Revision ID: 81b6367288bf
Revises: 
Create Date: 2024-07-15 10:58:17.278305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81b6367288bf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "BOOKED",
                "MAINTENANCE",
                "OCCUPIED",
                "CLEANING",
                name="room_status",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room")),
        sa.UniqueConstraint("number", name=op.f("uq_room_number")),
    )
    op.create_table(
        "booking",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("guest_id", sa.Integer(), nullable=False),
        sa.Column("check_in_date", sa.Date(), nullable=False),
        sa.Column("check_out_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CANCELED", "FINISHED", name="booking_status"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["room.id"], name=op.f("fk_booking_room_id_room")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking")),
    )
    op.create_table(
        "roomavailabledate",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["room.id"], name=op.f("fk_room_available_date_room_id_room")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_available_date")),
    )
    op.create_table(
        "roomtypeinfo",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["room.id"], name=op.f("fk_room_type_info_room_id_room")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_type_info")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roomtypeinfo")
    op.drop_table("roomavailabledate")
    op.drop_table("booking")
    op.drop_table("room")
    # ### end Alembic commands ###
