"""empty message

Revision ID: 230f50bd7e74
Revises: 1402b0cbedc2
Create Date: 2024-07-19 14:38:49.558146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230f50bd7e74'
down_revision: Union[str, None] = '1402b0cbedc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_booking_room_id_check_in_date_check_out_date'), 'booking', ['room_id', 'check_in_date', 'check_out_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_booking_room_id_check_in_date_check_out_date'), 'booking', type_='unique')
    # ### end Alembic commands ###
