"""Changes password_hash field type

Revision ID: 73531dff1018
Revises: 577e20c1fb1d
Create Date: 2024-07-13 09:01:27.621604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73531dff1018'
down_revision: Union[str, None] = '577e20c1fb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN "password_hash" TYPE BYTEA USING "password_hash"::bytea')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN "password_hash" TYPE VARCHAR USING "password_hash"::varchar')
    # ### end Alembic commands ###
