"""Add columns 'active' and 'admin'

Revision ID: 577e20c1fb1d
Revises: f8a07f6541be
Create Date: 2024-07-13 08:08:05.113755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577e20c1fb1d'
down_revision: Union[str, None] = 'f8a07f6541be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user', sa.Column('admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
